services:
  api_db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: ${API_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${API_DB_NAME}
      MARIADB_USER: ${API_DB_USER}
      MARIADB_PASSWORD: ${API_DB_PASSWORD}
    ports:
      - '${API_DB_PORT}:3306'
    volumes:
      - api_db_data:/var/lib/mysql
      - ./db-init/api-init.sh:/docker-entrypoint-initdb.d/init.sh
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  auth_db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${AUTH_DB_NAME}
      MARIADB_USER: ${AUTH_DB_USER}
      MARIADB_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - '${AUTH_DB_PORT}:3306'
    volumes:
      - auth_db_data:/var/lib/mysql
      - ./db-init/auth-init.sh:/docker-entrypoint-initdb.d/init.sh
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  api_db_data:
  auth_db_data:
