services:
  api_db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${API_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${API_DB_NAME}
      MARIADB_USER: ${API_DB_USER}
      MARIADB_PASSWORD: ${API_DB_PASSWORD}
    ports:
      - '${API_DB_PORT}:3306'
    volumes:
      - api_db_data:/var/lib/mysql
      - ./docker/db/api-init.sh:/docker-entrypoint-initdb.d/init.sh

  auth_db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${AUTH_DB_NAME}
      MARIADB_USER: ${AUTH_DB_USER}
      MARIADB_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - '${AUTH_DB_PORT}:3306'
    volumes:
      - auth_db_data:/var/lib/mysql
      - ./docker/db/auth-init.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  api_db_data:
  auth_db_data:
