#!/bin/bash
set -e

mysql -u root -p"$MARIADB_ROOT_PASSWORD" <<EOSQL
CREATE DATABASE IF NOT EXISTS \`$AUTH_DB_NAME\`;
CREATE USER IF NOT EXISTS '$AUTH_DB_USER'@'%' IDENTIFIED BY '$AUTH_DB_PASSWORD';
GRANT ALL PRIVILEGES ON \`$AUTH_DB_NAME\`.* TO '$AUTH_DB_USER'@'%';
FLUSH PRIVILEGES;
EOSQL

echo "Auth database initialized"